In [ ]:
import torch
from torch import nn

X = torch.tensor([
    [10], 
    [37.78]
], dtype=torch.float32 )

y = torch.tensor([
    [50],
    [100.0]
], dtype = torch.float32 )

# X1 = torch.tensor([ [10] ], dtype=torch.float32 ) # 섭씨 온도
# y1 = torch.tensor([ [50] ], dtype=torch.float32 ) # 화씨 변화 온도(레이블)

# X2 = torch.tensor([ [37.78] ], dtype=torch.float32 ) # 섭씨 온도
# y2 = torch.tensor([ [100.0] ], dtype=torch.float32 ) # 화씨 온도

model = nn.Linear( 1, 1 )

# 손실함수 지정
loss_fn = torch.nn.MSELoss()

# 최적화: 경사하강, 등..
optimizer = torch.optim.SGD( model.parameters(), lr=0.0001 )

# print('모델 가중치: ', model.weight )
# print('모델 매개변수(편향): ', model.bias )


for i in range( 0, 150000 ):
    # 훈련
    optimizer.zero_grad()
    outputs = model(X)
    loss = loss_fn( outputs, y ) # outputs = 훈련결과로 나온 예측값, 손실값을 계산함
    loss.backward() # 손실을 줄이기 위한 기울기를 볼때 사용, 기울기 계산
    optimizer.step()

    if i % 100 == 0:
        print( model.bias )
        print( model.weight )


print('====평가 모드 끄고 실제 모델을 적용====')

measurements = torch.tensor([
    [37.5]
], dtype=torch.float32 )

model.eval() # 훈련하지 않음
with torch.no_grad(): # 파이썬에서 torch.no_grad()만 실행해라는 문법?
    prediction = model( measurements )
    print( prediction )


Parameter containing:
tensor([0.3377], requires_grad=True)
Parameter containing:
tensor([[0.7222]], requires_grad=True)
Parameter containing:
tensor([0.5615], requires_grad=True)
Parameter containing:
tensor([[2.7837]], requires_grad=True)
Parameter containing:
tensor([0.7198], requires_grad=True)
Parameter containing:
tensor([[2.7788]], requires_grad=True)
Parameter containing:
tensor([0.8773], requires_grad=True)
Parameter containing:
tensor([[2.7738]], requires_grad=True)
Parameter containing:
tensor([1.0340], requires_grad=True)
Parameter containing:
tensor([[2.7689]], requires_grad=True)
Parameter containing:
tensor([1.1900], requires_grad=True)
Parameter containing:
tensor([[2.7641]], requires_grad=True)
Parameter containing:
tensor([1.3451], requires_grad=True)
Parameter containing:
tensor([[2.7592]], requires_grad=True)
Parameter containing:
tensor([1.4995], requires_grad=True)
Parameter containing:
tensor([[2.7544]], requires_grad=True)
Parameter containing:
tensor([1.6530], r